# vim: ts=2:sw=2:sts=2:et:ft=yaml.ansible
# -*- mode: yaml; yaml-indent-offset: 2; indent-tabs-mode: nil; -*-
---
changes_file: changelog.yaml
changes_format: combined
keep_fragments: false
mention_ancestor: true
new_plugins_after_name: removed_features
notesdir: fragments
prelude_section_name: release_summary
prelude_section_title: Release Summary
sanitize_changelog: true
sections:
  - [major_changes, Major Changes]
  - [minor_changes, Minor Changes]
  - [breaking_changes, Breaking Changes / Porting Guide]
  - [deprecated_features, Deprecated Features]
  - [removed_features, Removed Features (previously deprecated)]
  - [security_fixes, Security Fixes]
  - [bugfixes, Bugfixes]
  - [known_issues, Known Issues]
output:
  - file: CHANGELOG.rst
    format: rst
title: 'o0_o.windows'
trivial_section_name: trivial
use_fqcn: true
